dist: trusty
language: c
sudo: false
addons:
  apt:
    packages:
    - texinfo
cache:
  directories:
  - build
jobs:
  include:
  - stage: clean
    script:
      - make clean
  - stage: build toolchain
    script:
      - travis_wait 90 make toolchain_clean toolchain_build
  - stage: build tools
    script:
      - make tools_clean tools_build
  - stage: build sgdk
    script:
      - export GENDEV=`pwd`/build
      - make sgdk_clean sgdk_build
      - make sgdk_samples
  - stage: release to github
    script: 
    - echo "Deploying to github..."
    - make release
    deploy:
      provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      skip_cleanup: true
      file_glob: true
      file:
        - dist/gendev_*.txz
        - dist/gendev_*_all.deb
      on:
        tags: true
        repo: kubilus1/gendev
